{
 "title": "OpenHIM: Transactions",
 "tags": [ "openhim" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(openhim_transactions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current transactions per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(openhim_transactions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions by status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(status) (openhim_transactions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions by client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(client) (openhim_transactions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per second by channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(channel) (rate(openhim_transactions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per second by client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(client) (rate(openhim_transactions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response times by channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(channel) (rate(openhim_request_duration_sum[$__rate_interval])) / sum by(channel) (rate(openhim_request_duration_count{status=\"Successful\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}