// Generated by CoffeeScript 1.6.3
(function() {
  var http, mockServer;

  http = require("http");

  mockServer = http.createServer(function(req, res) {
    res.writeHead(201, {
      "Content-Type": "text/plain"
    });
    res.write("Mock response body\n");
    res.end();
    return console.log("Responded!");
  });

  mockServer.listen(9876, function() {
    return console.log("Mock server listening on 9876");
  });

}).call(this);
