#!/bin/bash
set -x


USERNAME=openhim
HOME=/home/$USERNAME
SH=/bin/sh

chown -R  $USERNAME:$USERNAME $HOME/openhim-core-js

NPM=/usr/bin/npm
CURL=/usr/bin/curl
SRCDIR=/tmp/openhim-core-js/src/nvm
COREDIR=$HOME/openhim-core-js

cd $HOME

mkdir -p $SRCDIR
$CURL https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh -o $SRCDIR/install.sh
sudo -iu $USERNAME sh $SRCDIR/install.sh
sudo -iu $USERNAME sh $HOME/bin/install_node.sh


start mongodb 
start openhim-core
