#!/bin/bash
set -x


USERNAME=openhim
HOME=/home/$USERNAME

chown -R  $USERNAME:$USERNAME $HOME/openhim-core-js

NPM=/usr/bin/npm
CURL=/usr/bin/curl
SRCDIR=$HOME/src/nvm
COREDIR=$HOME/openhim-core-js

cd $HOME

mkdir -p $SRCDIR
$CURL https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh -o $SRCDIR/install.sh
chown -R $USERNAME:$USERNAME $SRCDIR

sudo -u $USERNAME sh $SRCDIR/install.sh

source "/$HOME/.nvm/nvm.sh"  

sudo -i -u $USERNAME nvm install 0.12
sudo -u $USERNAME nvm alias default 0.12
sudo -u $USERNAME nvm use 0.12

cd $COREDIR

sudo -u $USERNAME $NPM install 
sudo -u $USERNAME $NPM install -g grunt-cli grunt
#  grunt-coffeelint grunt-contrib-coffee grunt-contrib-clean grunt-mocha-cli grunt-contrib-watch
#sudo -u $USERNAME $NPM run-script prepublish
sudo -u $USERNAME grunt build

start mongodb 
start openhim-core
