#!/bin/bash
set -x


USERNAME=openhim
HOME=/home/$USERNAME
USERADD=/usr/sbin/useradd
ADDGROUP=/usr/sbin/addgroup


if id -u $1 >/dev/null 2>&1; then
    echo "user $USERNAME exists."
else
    echo "user $USERNAME does not exist. adding."
    $USERADD $USERNAME -m -s /bin/bash 
fi

#adduser  --gecos ""   $USERNAME


