#!/bin/bash
set -x


USERNAME=openhim
HOME=/home/$USERNAME
USERADD=/usr/sbin/useradd
ADDGROUP=/usr/sbin/addgroup


if id -u $USERNAME >/dev/null 2>&1; then
    echo "user $USERNAME exists."
else
    echo "user $USERNAME does not exist. adding."
    $USERADD  --quiet $USERNAME -m -s /bin/bash 
fi

if ! getent group $USERNAME >/dev/null; then
    echo "Creating group $USERNAME"
    $ADDGROUP --quiet --system $USERNAME
fi

echo "Add group $USERNAME to group $USERNAME"
$ADDUSER --quiet $USERNAME $USERNAME

exit 0



