# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.box_url = "http://atlas.hashicorp.com/ubuntu/boxes/trusty64"

	config.vm.network :bridged
	config.vm.forward_port 5000, 5000
	config.vm.forward_port 5001, 5001
	config.vm.forward_port 5050, 5050
	config.vm.forward_port 5051, 5051
	config.vm.forward_port 5052, 5052
	config.vm.forward_port 8080, 8080

	config.vm.share_folder "openhim-core-js", "/openhim-core-js", "../../../"

	config.vm.provision :shell do |shell|
		shell.inline = "mkdir -p /etc/puppet/modules;
			puppet module install willdurand/nodejs;
			puppet module install puppetlabs/mongodb"
	end

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "./"
		puppet.manifest_file  = "openhim-core-js.pp"
	end
end
