name: Scan IaC and compose files

on:
  schedule:
    - cron: '0 5 * * *'
  pull_request:

permissions:
  pull-requests: write

jobs:
  infrascan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run InfraScan
        uses: soldevelo/infrascan@v1
        with:
          scanner: comprehensive
          format: html
          out: infrascan-report.html

      - name: Upload InfraScan report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: infrascan-report
          path: infrascan-report.html
